export const createPopId = (text, pi, i) => `${text}-${pi}-${i}`.replace(/(\.|,|\?|!)/, '').trim().toLowerCase();

export const paragraphs = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sagittis sem eget metus tempus, sed posuere nibh mattis. Fusce vitae ultricies nibh. Fusce tincidunt ut velit a elementum. Suspendisse sollicitudin bibendum lorem sit amet finibus. Nullam feugiat nisl nec tristique pharetra. Maecenas fermentum mi eu justo commodo dignissim. Suspendisse feugiat eros quis urna aliquam rhoncus. Curabitur a nisi maximus, laoreet nunc et, mollis nunc.",
  "Aenean cursus justo eget magna pulvinar congue. Mauris luctus sed odio a fermentum. Praesent semper aliquam vehicula. Pellentesque vitae turpis mollis, posuere libero id, pharetra dolor. In eu commodo ipsum, eget ornare nibh. Curabitur vulputate sit amet augue a faucibus. Vestibulum at sagittis ante. Duis id sem at lacus congue aliquet. Aliquam ullamcorper dui lacus, ut commodo leo elementum at. Proin accumsan risus elit, malesuada fringilla libero mattis id. Ut at mauris pulvinar velit lobortis porttitor et quis tortor.",
  "Maecenas nec risus mattis, consequat mi eget, scelerisque arcu. Donec et semper nisl. Aenean tempor felis eros, vel laoreet mi sodales nec. Sed sit amet rutrum est. Cras vel ex mattis, vestibulum nisl varius, dictum sapien. In imperdiet, justo pharetra lobortis facilisis, lorem magna malesuada enim, eu commodo diam purus quis enim. Praesent sit amet sagittis mi. Morbi ut metus mattis, vestibulum ante vel, pellentesque eros. Sed nec justo et velit ultrices faucibus.",
  "Praesent ac fermentum odio. Suspendisse potenti. Donec ut egestas justo, ac imperdiet risus. Integer placerat ornare vestibulum. Duis dictum blandit tellus et blandit. Donec euismod, dolor sit amet lacinia euismod, nunc neque mollis velit, nec sagittis nisl risus eget lorem. Morbi risus purus, volutpat ut tellus id, bibendum gravida urna. Donec eget ipsum ex. In hac habitasse platea dictumst. Fusce nulla ex, sagittis sed sem nec, placerat aliquam neque. Maecenas pellentesque quam metus, molestie molestie tortor convallis ac. Quisque sagittis tortor non ex condimentum rhoncus. Pellentesque et ornare leo. Aenean magna lectus, tincidunt a bibendum quis, tristique nec erat. Fusce odio lacus, tincidunt quis congue in, pulvinar eget dolor.",
  "Vivamus ex diam, aliquam aliquet lacus vel, rhoncus vulputate justo. Cras euismod ligula purus, vitae tristique lectus commodo id. Proin ac consequat leo. Praesent justo diam, interdum id mi vel, accumsan eleifend purus. Vivamus molestie nisi id ligula pulvinar condimentum. Nulla facilisis nec odio sed faucibus. Maecenas vestibulum ex tortor, et suscipit turpis scelerisque nec. Cras elementum et tortor sagittis sagittis. Maecenas in pharetra metus, quis accumsan sem. Maecenas maximus nunc non euismod convallis. Proin venenatis commodo sem, et convallis mauris scelerisque a. Pellentesque vitae libero sapien. Donec non sem orci.",
  "Integer vitae felis odio. Pellentesque pretium turpis non suscipit auctor. Cras at tortor erat. Maecenas sodales in risus non sodales. Donec ultrices porta efficitur. Duis consequat dolor at viverra elementum. Donec id risus placerat, facilisis nunc facilisis, consectetur neque. Quisque euismod in nisi in lobortis. Suspendisse sit amet nulla non risus vestibulum porta. Nunc id lobortis leo. Suspendisse lorem purus, cursus ut est vitae, vulputate lobortis elit. Maecenas commodo lectus id quam semper porta. Donec id risus vitae nunc aliquam fringilla. Ut non euismod urna. Sed maximus convallis nisi, sit amet iaculis quam sagittis eu.",
  "Suspendisse eget enim pulvinar, ullamcorper justo ac, egestas augue. Vivamus laoreet commodo vulputate. Quisque tincidunt sodales tincidunt. Etiam ac odio sapien. Vestibulum lectus erat, ultrices ut nibh vitae, imperdiet malesuada neque. Morbi malesuada eleifend orci quis vestibulum. Sed sem nulla, vestibulum at pharetra ac, consequat vel metus. Sed sit amet fringilla lacus. Quisque magna ante, tincidunt sed posuere ut, bibendum sed neque. Nam ac urna a ipsum luctus dignissim id sit amet mi. Donec sed urna mollis, consequat sapien at, consequat risus. Vestibulum efficitur, dui quis sagittis finibus, tortor nisl convallis nulla, et condimentum erat risus ac nunc. Curabitur ultrices massa at auctor dapibus.",
  "Suspendisse rutrum rutrum metus, vehicula dignissim est rhoncus sed. Nullam quis velit non ligula venenatis maximus. Vestibulum in tempor odio, vel imperdiet neque. Proin feugiat lectus ac aliquet maximus. Phasellus ac tincidunt sem. Phasellus fermentum ut dui ut mollis. In finibus lorem at nisl luctus, quis venenatis odio varius. Integer id sapien arcu",
  "Donec lacinia orci vehicula convallis rhoncus. Aliquam erat est, mollis pulvinar nisl sed, venenatis pretium lectus. Nullam vel neque tincidunt, volutpat felis at, gravida turpis. Aliquam dui tortor, vulputate ut ipsum non, porta iaculis elit. Sed mauris leo, cursus in viverra id, posuere nec purus. Nullam facilisis massa nunc, eleifend laoreet purus placerat eget. Mauris imperdiet dolor fringilla lacus maximus, vel malesuada ex aliquam. Aliquam dolor metus, porttitor sit amet turpis ut, convallis placerat dui. Maecenas massa ante, fringilla vitae eros eget, eleifend ultrices urna. Phasellus finibus turpis eu malesuada sollicitudin.",
  "Etiam laoreet justo eget ipsum convallis elementum eu quis erat. Integer aliquam, orci in congue sagittis, nisi felis tincidunt mi, dignissim blandit tortor risus eget justo. Morbi accumsan eu turpis at cursus. Mauris erat purus, fringilla eu tempus et, accumsan quis nunc. Nunc nulla lacus, condimentum ut elit viverra, auctor pharetra urna. Maecenas mollis massa ut dolor molestie venenatis. Pellentesque volutpat egestas ultrices. Vivamus a mi nec nunc fermentum porta.",
];